const state={chat:null,files:[],busy:false}; const $=id=>document.getElementById(id);
async function api(path,options={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const v=await r.json();if(!r.ok)throw new Error(v.error||`HTTP ${r.status}`);return v}
function render(){const box=$('messages');box.textContent='';for(const m of state.chat?.messages||[]){const e=document.createElement('div');e.className='message '+m.sender;const p=document.createElement('p');p.textContent=m.v;e.append(p);box.append(e)}box.scrollTop=box.scrollHeight;$('files').textContent=state.files.map(f=>f.name).join('、')}
async function refresh(){const list=await api('/api/conversations');if(!state.chat){state.chat=list[0]||await api('/api/conversations',{method:'POST',body:'{}'})}else{const found=list.find(x=>x.id===state.chat.id);if(found)state.chat=found}render()}
async function status(){const v=await api('/api/status');$('status').textContent=v.codex_found?'已找到本地 Codex，可开始测试':'未找到 Codex：请先安装并使用 ChatGPT 登录'}
function asPayload(file){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok({name:file.name,data:String(r.result).split(',')[1]});r.onerror=no;r.readAsDataURL(file)})}
function resetDecision(){$('status').textContent='新聊天已建立，可以开始测试';$('decision').textContent='尚未运行';$('decision').className='decision idle';$('transferReason').textContent='无';$('decisionReason').textContent='无';$('diagnostic').textContent='尚未运行';$('citations').textContent=''}
async function send(){if(state.busy||(!$('input').value.trim()&&!state.files.length))return;state.busy=true;$('send').disabled=true;$('status').textContent='检索资料并生成回答…';try{const images=await Promise.all(state.files.map(asPayload));const value=await api(`/api/conversations/${state.chat.id}/messages`,{method:'POST',body:JSON.stringify({text:$('input').value,images,expected_version:state.chat.version})});state.chat=value.conversation;$('input').value='';state.files=[];$('decision').textContent=value.action==='reply_then_transfer'?'回复后转人工':'正常回复';$('decision').className='decision '+value.action;$('transferReason').textContent=value.transfer_reason||'none';$('decisionReason').textContent=value.reason||'无';$('diagnostic').textContent=JSON.stringify(value.diagnostic,null,2);$('citations').textContent='';for(const name of value.citations){const li=document.createElement('li');li.textContent=name;$('citations').append(li)}$('status').textContent='回答完成；这里只显示决定，不操作千牛';render()}catch(e){await refresh();$('status').textContent='失败：'+e.message}finally{state.busy=false;$('send').disabled=false}}
$('newChat').onclick=async()=>{state.chat=await api('/api/conversations',{method:'POST',body:'{}'});resetDecision();render()};$('deleteChat').onclick=async()=>{if(state.chat&&confirm('删除当前聊天记录和图片？')){await api('/api/conversations/'+state.chat.id,{method:'DELETE'});state.chat=null;resetDecision();await refresh()}};$('deleteAll').onclick=async()=>{if(confirm('清空全部聊天记录和图片？')){await api('/api/conversations',{method:'DELETE'});state.chat=null;resetDecision();await refresh()}};
$('send').onclick=send;$('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('images').onchange=e=>{state.files=[...e.target.files];render()};const drop=$('drop');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('over')});drop.addEventListener('dragleave',()=>drop.classList.remove('over'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('over');state.files=[...e.dataTransfer.files].filter(f=>f.type.startsWith('image/'));render()});status();refresh();
